import { Language } from './types';

export const CROP_TYPES = [
  "Wheat", "Rice", "Corn", "Potatoes", "Tomatoes", "Onions", "Soybeans", "Cotton", "Sugarcane", "Mustard", "Pulses", "Spices"
];

export const LOCATIONS = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.ENGLISH]: {
    welcome: "Welcome to AgroLink",
    subtitle: "Connecting Farmers and Vendors simply and securely.",
    login: "Login with ID",
    register: "Register New Account",
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    matches: "My Matches",
    chat: "Messages",
    profile: "Profile",
    assistant: "AgroBot AI",
    logout: "Logout",
    farmer: "Farmer",
    vendor: "Vendor",
    selectRole: "Select Your Role",
    cropsGrown: "Crops I Grow",
    cropsNeeded: "Crops I Need",
    price: "Price",
    area: "State / Region",
    save: "Save Details",
    trustScore: "Trust Score",
    report: "Report User",
    rate: "Rate User",
    sendMessage: "Send Message",
    noMatches: "No matches found yet. Try updating your items.",
    recentChats: "Recent Chats",
    priceTrend: "Market Price Trends",
    aiPrompt: "Ask AgroBot about crop prices, weather, or farming tips...",
    ask: "Ask",
    loading: "Thinking...",
    idCopied: "ID Copied! Save this to login later.",
    anonymous: "Your Anonymous ID",
    enterId: "Enter your Anonymous ID",
    findMatches: "Find Matches",
    filterByCrop: "Filter by Crop",
    userIdNotFound: "User ID not found. Please register first.",
    addOneItem: "Please add at least one crop/item.",
    regSuccess: "Registration Successful!",
    goToDashboard: "Go to Dashboard",
    realName: "Real Name (Private)",
    yourName: "Your Name",
    cropType: "Crop Type",
    quantity: "Quantity",
    addToList: "Add to List",
    added: "Added",
    qtyPlaceholder: "e.g. 500kg",
    idPlaceholder: "e.g. farmer1234",
    welcomeBack: "Welcome back,",
    potentialMatches: "Potential Matches",
    listedItems: "Listed Items",
    marketTrend: "Market Trend",
    recentMatches: "Recent Matches",
    viewAll: "View All",
    grows: "Grows",
    needs: "Needs",
    perKg: "per kg",
    trust: "Trust",
    allCrops: "All Crops",
    allLocations: "All Locations",
    noMatchesCriteria: "No farmers or vendors found matching these criteria.",
    noConversations: "No conversations yet.",
    tapToChat: "Tap to chat",
    online: "Online",
    typeMessage: "Type a message...",
    selectConversation: "Select a conversation to start chatting",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    productInfo: "Product Info",
    add: "Add",
    newItem: "New Item",
    cropLabel: "Crop",
    priceLabel: "Price",
    qtyLabel: "Qty",
    noItems: "No items listed.",
    trustSafety: "Trust & Safety",
    verifiedMember: "Verified Member since",
    reviews: "Reviews",
    writeReview: "Write a review...",
    submitReview: "Submit Review",
    noReviews: "No reviews yet.",
    confirmDelete: "Are you sure you want to delete this item?",
    aiIntro: "Namaste! I am AgroBot. I can help you with crop prices, farming tips, or weather advice. What's on your mind?",
    poweredBy: "Powered by Gemini 2.5 Flash",
    aiError: "Sorry, I had trouble thinking. Please try again.",
    expandSidebar: "Expand Sidebar",
    collapseSidebar: "Collapse Sidebar",
    selectOption: "Select...",
    photo: "Photo",
    // Crops
    Wheat: "Wheat",
    Rice: "Rice",
    Corn: "Corn",
    Potatoes: "Potatoes",
    Tomatoes: "Tomatoes",
    Onions: "Onions",
    Soybeans: "Soybeans",
    Cotton: "Cotton",
    Sugarcane: "Sugarcane",
    Mustard: "Mustard",
    Pulses: "Pulses",
    Spices: "Spices"
  },
  [Language.HINDI]: {
    welcome: "एग्रोलिंक में आपका स्वागत है",
    subtitle: "किसानों और विक्रेताओं को सरलता और सुरक्षित रूप से जोड़ना।",
    login: "आईडी के साथ लॉगिन करें",
    register: "नया खाता रजिस्टर करें",
    dashboard: "डैशबोर्ड",
    marketplace: "बाज़ार",
    matches: "मेरे मेल",
    chat: "संदेश",
    profile: "प्रोफाइल",
    assistant: "एग्रो-बोट एआई",
    logout: "लॉग आउट",
    farmer: "किसान",
    vendor: "विक्रेता",
    selectRole: "अपनी भूमिका चुनें",
    cropsGrown: "फसलें जो मैं उगाता हूँ",
    cropsNeeded: "फसलें जिनकी मुझे आवश्यकता है",
    price: "कीमत",
    area: "राज्य / क्षेत्र",
    save: "विवरण सहेजें",
    trustScore: "विश्वास स्कोर",
    report: "उपयोगकर्ता की रिपोर्ट करें",
    rate: "उपयोगकर्ता को रेट करें",
    sendMessage: "संदेश भेजें",
    noMatches: "अभी तक कोई मेल नहीं मिला। अपनी वस्तुओं को अपडेट करने का प्रयास करें।",
    recentChats: "हाल की बातचीत",
    priceTrend: "बाजार मूल्य रुझान",
    aiPrompt: "एग्रो-बोट से फसल की कीमतों, मौसम या खेती के सुझावों के बारे में पूछें...",
    ask: "पूछें",
    loading: "सोच रहा हूँ...",
    idCopied: "आईडी कॉपी की गई! बाद में लॉगिन करने के लिए इसे सहेजें।",
    anonymous: "आपकी अनाम आईडी",
    enterId: "अपनी अनाम आईडी दर्ज करें",
    findMatches: "मेल खोजें",
    filterByCrop: "फसल के अनुसार फ़िल्टर करें",
    userIdNotFound: "उपयोगकर्ता आईडी नहीं मिली। कृपया पहले पंजीकरण करें।",
    addOneItem: "कृपया कम से कम एक फसल/वस्तु जोड़ें।",
    regSuccess: "पंजीकरण सफल!",
    goToDashboard: "डैशबोर्ड पर जाएं",
    realName: "असली नाम (निजी)",
    yourName: "आपका नाम",
    cropType: "फसल का प्रकार",
    quantity: "मात्रा",
    addToList: "सूची में जोड़ें",
    added: "जोड़ा गया",
    qtyPlaceholder: "उदा. 500 किग्रा",
    idPlaceholder: "उदा. farmer1234",
    welcomeBack: "वापसी पर स्वागत है,",
    potentialMatches: "संभावित मेल",
    listedItems: "सूचीबद्ध वस्तुएं",
    marketTrend: "बाजार का रुझान",
    recentMatches: "हाल के मेल",
    viewAll: "सभी देखें",
    grows: "उगाता है",
    needs: "चाहिए",
    perKg: "प्रति किलो",
    trust: "विश्वास",
    allCrops: "सभी फसलें",
    allLocations: "सभी स्थान",
    noMatchesCriteria: "इन मानदंडों से मेल खाने वाले कोई किसान या विक्रेता नहीं मिले।",
    noConversations: "अभी तक कोई बातचीत नहीं।",
    tapToChat: "चैट करने के लिए टैप करें",
    online: "ऑनलाइन",
    typeMessage: "एक संदेश लिखें...",
    selectConversation: "चैट शुरू करने के लिए एक बातचीत चुनें",
    editProfile: "प्रोफ़ाइल संपादित करें",
    cancel: "रद्द करें",
    productInfo: "उत्पाद जानकारी",
    add: "जोड़ें",
    newItem: "नई वस्तु",
    cropLabel: "फसल",
    priceLabel: "कीमत",
    qtyLabel: "मात्रा",
    noItems: "कोई वस्तु सूचीबद्ध नहीं है।",
    trustSafety: "विश्वास और सुरक्षा",
    verifiedMember: "सत्यापित सदस्य",
    reviews: "समीक्षाएं",
    writeReview: "एक समीक्षा लिखें...",
    submitReview: "समीक्षा जमा करें",
    noReviews: "अभी तक कोई समीक्षा नहीं।",
    confirmDelete: "क्या आप वाकई इस वस्तु को हटाना चाहते हैं?",
    aiIntro: "नमस्ते! मैं एग्रो-बोट हूँ। मैं फसल की कीमतों, खेती के सुझावों या मौसम की सलाह में आपकी मदद कर सकता हूँ। आपके मन में क्या है?",
    poweredBy: "जेमिनी 2.5 फ्लैश द्वारा संचालित",
    aiError: "क्षमा करें, मुझे सोचने में परेशानी हुई। कृपया पुनः प्रयास करें।",
    expandSidebar: "साइडबार बढ़ाएं",
    collapseSidebar: "साइडबार संक्षिप्त करें",
    selectOption: "चुनें...",
    photo: "फोटो",
    // Crops
    Wheat: "गेहूं",
    Rice: "चावल",
    Corn: "मक्का",
    Potatoes: "आलू",
    Tomatoes: "टमाटर",
    Onions: "प्याज",
    Soybeans: "सोयाबीन",
    Cotton: "कपास",
    Sugarcane: "गन्ना",
    Mustard: "सरसों",
    Pulses: "दालें",
    Spices: "मसाले"
  },
  [Language.MARATHI]: {
    welcome: "AgroLink मध्ये आपले स्वागत आहे",
    subtitle: "शेतकरी आणि विक्रेत्यांना सोप्या आणि सुरक्षित पद्धतीने जोडणे.",
    login: "आयडी सह लॉगिन करें",
    register: "नवीन खाते नोंदणी करा",
    dashboard: "डॅशबोर्ड",
    marketplace: "बाजारपेठ",
    matches: "माझे जुळवणी",
    chat: "संदेश",
    profile: "प्रोफाइल",
    assistant: "अ‍ॅग्रो-बॉट एआय",
    logout: "बाहेर पडणे",
    farmer: "शेतकरी",
    vendor: "विक्रेता",
    selectRole: "तुमची भूमिका निवडा",
    cropsGrown: "मी पिकवलेली पिके",
    cropsNeeded: "मला आवश्यक पिके",
    price: "किंमत",
    area: "राज्य / प्रदेश",
    save: "तपशील जतन करा",
    trustScore: "विश्वास गुण",
    report: "वापरकर्ता रिपोर्ट करा",
    rate: "वापरकर्ता रेट करा",
    sendMessage: "संदेश पाठवा",
    noMatches: "अद्याप कोणतीही जुळवणी आढळली नाही. आपल्या वस्तू अद्यतनित करण्याचा प्रयत्न करा.",
    recentChats: "अलीकडील गप्पा",
    priceTrend: "बाजार भाव ट्रेंड",
    aiPrompt: "अ‍ॅग्रो-बॉटला पीक किंमती, हवामान किंवा शेती टिप्स बद्दल विचारा...",
    ask: "विचारा",
    loading: "विचार करत आहे...",
    idCopied: "आयडी कॉपी केला! नंतर लॉगिन करण्यासाठी जतन करा.",
    anonymous: "तुमचा निनावी आयडी",
    enterId: "तुमचा निनावी आयडी प्रविष्ट करा",
    findMatches: "जुळवणी शोधा",
    filterByCrop: "पिकांनुसार फिल्टर करा",
    userIdNotFound: "वापरकर्ता आयडी आढळला नाही. कृपया प्रथम नोंदणी करा.",
    addOneItem: "कृपया किमान एक पीक/वस्तू जोडा.",
    regSuccess: "नोंदणी यशस्वी!",
    goToDashboard: "डॅशबोर्डवर जा",
    realName: "खरे नाव (खाजगी)",
    yourName: "तुमचे नाव",
    cropType: "पिकाचा प्रकार",
    quantity: "प्रमाण",
    addToList: "यादीत जोडा",
    added: "जोडले",
    qtyPlaceholder: "उदा. 500 किलो",
    idPlaceholder: "उदा. farmer1234",
    welcomeBack: "परत स्वागत आहे,",
    potentialMatches: "संभाव्य जुळवणी",
    listedItems: "सूचीबद्ध वस्तू",
    marketTrend: "बाजार कल",
    recentMatches: "अलीकडील जुळवणी",
    viewAll: "सर्व पहा",
    grows: "पिकवतो",
    needs: "गरज आहे",
    perKg: "प्रति किलो",
    trust: "विश्वास",
    allCrops: "सर्व पिके",
    allLocations: "सर्व ठिकाणे",
    noMatchesCriteria: "या निकषांशी जुळणारे कोणतेही शेतकरी किंवा विक्रेते आढळले नाहीत.",
    noConversations: "अद्याप कोणताही संवाद नाही.",
    tapToChat: "चॅट करण्यासाठी टॅप करा",
    online: "ऑनलाइन",
    typeMessage: "संदेश टाइप करा...",
    selectConversation: "चॅटिंग सुरू करण्यासाठी संभाषण निवडा",
    editProfile: "प्रोफाइल संपादित करा",
    cancel: "रद्द करा",
    productInfo: "उत्पादन माहिती",
    add: "जोडा",
    newItem: "नवीन वस्तू",
    cropLabel: "पीक",
    priceLabel: "किंमत",
    qtyLabel: "प्रमाण",
    noItems: "कोणत्याही वस्तू सूचीबद्ध नाहीत.",
    trustSafety: "विश्वास आणि सुरक्षा",
    verifiedMember: "पासून सत्यापित सदस्य",
    reviews: "पुनरावलोकने",
    writeReview: "पुनरावलोकन लिहा...",
    submitReview: "पुनरावलोकन सबमिट करा",
    noReviews: "अद्याप कोणतीही पुनरावलोकने नाहीत.",
    confirmDelete: "तुम्हाला नक्की ही वस्तू काढायची आहे का?",
    aiIntro: "नमस्ते! मी अ‍ॅग्रो-बॉट आहे. मी तुम्हाला पीक किंमती, शेती टिप्स किंवा हवामान सल्ल्यामध्ये मदत करू शकतो. तुमच्या मनात काय आहे?",
    poweredBy: "जेमिनी 2.5 फ्लॅश द्वारे समर्थित",
    aiError: "क्षमस्व, मला विचार करण्यात अडचण आली. कृपया पुन्हा प्रयत्न करा.",
    expandSidebar: "साइडबार वाढवा",
    collapseSidebar: "साइडबार कमी करा",
    selectOption: "निवडा...",
    photo: "फोटो",
    // Crops
    Wheat: "गहू",
    Rice: "तांदूळ",
    Corn: "मका",
    Potatoes: "बटाटे",
    Tomatoes: "टोमॅटो",
    Onions: "कांदा",
    Soybeans: "सोयाबीन",
    Cotton: "कापूस",
    Sugarcane: "ऊस",
    Mustard: "मोहरी",
    Pulses: "डाळी",
    Spices: "मसाले"
  },
  [Language.BENGALI]: {
    welcome: "AgroLink-এ স্বাগতম",
    subtitle: "কৃষক এবং বিক্রেতাদের সহজে এবং নিরাপদে সংযুক্ত করা।",
    login: "আইডি দিয়ে লগইন করুন",
    register: "নতুন অ্যাকাউন্ট নিবন্ধন করুন",
    dashboard: "ড্যাশবোর্ড",
    marketplace: "মার্কেটপ্লেস",
    matches: "আমার ম্যাচ",
    chat: "বার্তা",
    profile: "প্রোফাইল",
    assistant: "অ্যাগ্রো-বট এআই",
    logout: "লগ আউট",
    farmer: "কৃষক",
    vendor: "বিক्रेতা",
    selectRole: "আপনার ভূমিকা নির্বাচন করুন",
    cropsGrown: "যে ফসল আমি ফলাই",
    cropsNeeded: "যে ফসল আমার প্রয়োজন",
    price: "দাম",
    area: "রাজ্য / অঞ্চল",
    save: "বিবরণ সংরক্ষণ করুন",
    trustScore: "বিশ্বাস স্কোর",
    report: "ব্যবহারকারী রিপোর্ট করুন",
    rate: "ব্যবহারকারী রেট করুন",
    sendMessage: "বার্তা পাঠান",
    noMatches: "এখনও কোনো ম্যাচ পাওয়া যায়নি। আপনার আইটেম আপডেট করার চেষ্টা করুন।",
    recentChats: "সাম্প্রতিক চ্যাট",
    priceTrend: "বাজার মূল্যের প্রবণতা",
    aiPrompt: "অ্যাগ্রো-বটকে ফসলের দাম, আবহাওয়া বা চাষের পরামর্শ সম্পর্কে জিজ্ঞাসা করুন...",
    ask: "জিজ্ঞাসা করুন",
    loading: "ভাবছে...",
    idCopied: "আইডি কপি করা হয়েছে! পরে লগইন করার জন্য এটি সংরক্ষণ করুন।",
    anonymous: "আপনার বেনামী আইডি",
    enterId: "আপনার বেনামী আইডি লিখুন",
    findMatches: "ম্যাচ খুঁজুন",
    filterByCrop: "ফসল দ্বারা ফিল্টার করুন",
    userIdNotFound: "ব্যবহারকারী আইডি পাওয়া যায়নি। দয়া করে প্রথমে নিবন্ধন করুন।",
    addOneItem: "দয়া করে অন্তত একটি ফসল/আইটেম যোগ করুন।",
    regSuccess: "নিবন্ধন সফল!",
    goToDashboard: "ড্যাশবোর্ডে যান",
    realName: "আসল নাম (ব্যক্তিগত)",
    yourName: "আপনার নাম",
    cropType: "ফসলের ধরন",
    quantity: "পরিমাণ",
    addToList: "তালিকায় যোগ করুন",
    added: "যোগ করা হয়েছে",
    qtyPlaceholder: "যেমন ৫০০ কেজি",
    idPlaceholder: "যেমন farmer1234",
    welcomeBack: "স্বাগতম,",
    potentialMatches: "সম্ভাব্য ম্যাচ",
    listedItems: "তালিকাভুক্ত আইটেম",
    marketTrend: "বাজারের প্রবণতা",
    recentMatches: "সাম্প্রতিক ম্যাচ",
    viewAll: "সব দেখুন",
    grows: "ফলায়",
    needs: "প্রয়োজন",
    perKg: "প্রতি কেজি",
    trust: "বিশ্বাস",
    allCrops: "সব ফসল",
    allLocations: "সব এলাকা",
    noMatchesCriteria: "এই মানদণ্ডগুলির সাথে মেলা কোনো কৃষক বা বিক্রেতা পাওয়া যায়নি।",
    noConversations: "এখনও কোনো কথোপকথন নেই।",
    tapToChat: "চ্যাট করতে ট্যাপ করুন",
    online: "অনলাইন",
    typeMessage: "একটি বার্তা লিখুন...",
    selectConversation: "চ্যাট শুরু করতে একটি কথোপকথন নির্বাচন করুন",
    editProfile: "প্রোফাইল সম্পাদনা করুন",
    cancel: "বাতিল করুন",
    productInfo: "পণ্যের তথ্য",
    add: "যোগ করুন",
    newItem: "নতুন আইটেম",
    cropLabel: "ফসল",
    priceLabel: "দাম",
    qtyLabel: "পরিমাণ",
    noItems: "কোনো আইটেম তালিকাভুক্ত নেই।",
    trustSafety: "বিশ্বাস ও নিরাপত্তা",
    verifiedMember: "যাচাইকৃত সদস্য",
    reviews: "পর্যালোচনা",
    writeReview: "একটি পর্যালোচনা লিখুন...",
    submitReview: "পর্যালোচনা জমা দিন",
    noReviews: "এখনও কোনো পর্যালোচনা নেই।",
    confirmDelete: "আপনি কি নিশ্চিত যে আপনি এই আইটেমটি মুছে ফেলতে চান?",
    aiIntro: "নমস্কার! আমি অ্যাগ্রো-বট। আমি ফসলের দাম, চাষের টিপস বা আবহাওয়ার পরামর্শে আপনাকে সাহায্য করতে পারি। আপনার মনে কি আছে?",
    poweredBy: "জেমিনি ২.৫ ফ্ল্যাশ দ্বারা চালিত",
    aiError: "দুঃখিত, আমার ভাবতে সমস্যা হচ্ছিল। দয়া করে আবার চেষ্টা করুন।",
    expandSidebar: "সাইডबार প্রসারিত করুন",
    collapseSidebar: "সাইডबार সঙ্কুচিত করুন",
    selectOption: "নির্বাচন করুন...",
    photo: "ছবি",
    // Crops
    Wheat: "গম",
    Rice: "চাল",
    Corn: "ভুট্টা",
    Potatoes: "আলু",
    Tomatoes: "টমেটো",
    Onions: "পেঁয়াজ",
    Soybeans: "সয়াবিন",
    Cotton: "তুলা",
    Sugarcane: "আখ",
    Mustard: "সরিষা",
    Pulses: "ডাল",
    Spices: "মসলা"
  },
  [Language.TAMIL]: {
    welcome: "AgroLink-க்கு வரவேற்கிறோம்",
    subtitle: "விவசாயிகள் மற்றும் விற்பனையாளர்களை எளிமையாகவும் பாதுகாப்பாகவும் இணைத்தல்.",
    login: "ஐடி மூலம் உள்நுழையவும்",
    register: "புதிய கணக்கை பதிவு செய்யவும்",
    dashboard: "டாஷ்போர்டு",
    marketplace: "சந்தை",
    matches: "என் பொருத்தங்கள்",
    chat: "செய்திகள்",
    profile: "சுயவிவரம்",
    assistant: "அக்ரோ-பாட் AI",
    logout: "வெளியேறு",
    farmer: "விவசாயி",
    vendor: "விற்பனையாளர்",
    selectRole: "உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்",
    cropsGrown: "நான் பயிரிடும் பயிர்கள்",
    cropsNeeded: "எனக்குத் தேவையான பயிர்கள்",
    price: "விலை",
    area: "மாநிலம் / பிராந்தியம்",
    save: "விவரங்களைச் சேமிக்கவும்",
    trustScore: "நம்பிக்கை மதிப்பெண்",
    report: "புகாரளிக்கவும்",
    rate: "மதிப்பிடவும்",
    sendMessage: "செய்தி அனுப்பவும்",
    noMatches: "இதுவரை பொருத்தங்கள் இல்லை. உங்கள் பொருட்களை புதுப்பிக்கவும்.",
    recentChats: "சமீபத்திய உரையாடல்கள்",
    priceTrend: "சந்தை விலை நிலவரம்",
    aiPrompt: "பயிர் விலைகள், வானிலை அல்லது விவசாய குறிப்புகள் பற்றி அக்ரோ-பாட்-இடம் கேட்கவும்...",
    ask: "கேட்கவும்",
    loading: "யோசிக்கிறது...",
    idCopied: "ஐடி நகலெடுக்கப்பட்டது! பின்னர் உள்நுழைய இதைச் சேமிக்கவும்.",
    anonymous: "உங்கள் அநாமதேய ஐடி",
    enterId: "உங்கள் அநாமதேய ஐடியை உள்ளிடவும்",
    findMatches: "பொருத்தங்களைக் கண்டறியவும்",
    filterByCrop: "பயிர் மூலம் வடிகட்டவும்",
    userIdNotFound: "பயனர் ஐடி கிடைக்கவில்லை. முதலில் பதிவு செய்யவும்.",
    addOneItem: "குறைந்தபட்சம் ஒரு பயிர்/பொருளைச் சேர்க்கவும்.",
    regSuccess: "பதிவு வெற்றிகரமாக முடிந்தது!",
    goToDashboard: "டாஷ்போர்டுக்குச் செல்லவும்",
    realName: "உண்மையான பெயர் (தனிப்பட்டது)",
    yourName: "உங்கள் பெயர்",
    cropType: "பயிர் வகை",
    quantity: "அளவு",
    addToList: "பட்டியலில் சேர்க்கவும்",
    added: "சேர்க்கப்பட்டது",
    qtyPlaceholder: "எ.கா. 500 கிலோ",
    idPlaceholder: "எ.கா. farmer1234",
    welcomeBack: "மீண்டும் வருக,",
    potentialMatches: "சாத்தியமான பொருத்தங்கள்",
    listedItems: "பட்டியலிடப்பட்ட பொருட்கள்",
    marketTrend: "சந்தை போக்கு",
    recentMatches: "சமீபத்திய பொருத்தங்கள்",
    viewAll: "அனைத்தையும் பார்க்க",
    grows: "பயிரிடுகிறார்",
    needs: "தேவை",
    perKg: "கிலோ ஒன்றுக்கு",
    trust: "நம்பிக்கை",
    allCrops: "அனைத்து பயிர்கள்",
    allLocations: "அனைத்து இடங்கள்",
    noMatchesCriteria: "இந்த நிபந்தனைகளுக்கு பொருந்தக்கூடிய விவசாயிகள் அல்லது விற்பனையாளர்கள் இல்லை.",
    noConversations: "உரையாடல்கள் ஏதுமில்லை.",
    tapToChat: "அரட்டையடிக்க தட்டவும்",
    online: "ஆன்லைன்",
    typeMessage: "ஒரு செய்தியை தட்டச்சு செய்யவும்...",
    selectConversation: "அரட்டையைத் தொடங்க ஒரு உரையாடலைத் தேர்ந்தெடுக்கவும்",
    editProfile: "சுயவிவரத்தைத் திருத்தவும்",
    cancel: "ரத்துசெய்",
    productInfo: "தயாரிப்பு தகவல்",
    add: "சேர்",
    newItem: "புதிய பொருள்",
    cropLabel: "பயிர்",
    priceLabel: "விலை",
    qtyLabel: "அளவு",
    noItems: "பொருட்கள் எதுவும் பட்டியலிடப்படவில்லை.",
    trustSafety: "நம்பிக்கை மற்றும் பாதுகாப்பு",
    verifiedMember: "சரிபார்க்கப்பட்ட உறுப்பினர்",
    reviews: "மதிப்புரைகள்",
    writeReview: "மதிப்புரையை எழுதவும்...",
    submitReview: "மதிப்புரையை சமர்ப்பிக்கவும்",
    noReviews: "மதிப்புரைகள் ஏதுமில்லை.",
    confirmDelete: "இந்த பொருளை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
    aiIntro: "வணக்கம்! நான் அக்ரோ-பாட். பயிர் விலைகள், விவசாய குறிப்புகள் அல்லது வானிலை ஆலோசனைகளில் நான் உங்களுக்கு உதவ முடியும்.",
    poweredBy: "ஜெமினி 2.5 ஃப்ளாஷ் மூலம் இயக்கப்படுகிறது",
    aiError: "மன்னிக்கவும், சிந்திப்பதில் சிக்கல் ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    expandSidebar: "பக்கப்பட்டியை விரிக்கவும்",
    collapseSidebar: "பக்கப்பட்டியை சுருக்கவும்",
    selectOption: "தேர்ந்தெடு...",
    photo: "புகைப்படம்",
    // Crops
    Wheat: "கோதுமை",
    Rice: "அரிசி",
    Corn: "சோளம்",
    Potatoes: "உருளைக்கிழங்கு",
    Tomatoes: "தக்காளி",
    Onions: "வெங்காயம்",
    Soybeans: "சோயாபீன்ஸ்",
    Cotton: "பருத்தி",
    Sugarcane: "கரும்பு",
    Mustard: "கடுகு",
    Pulses: "பருப்பு வகைகள்",
    Spices: "மசாலா பொருட்கள்"
  },
  [Language.TELUGU]: {
    welcome: "AgroLink-కు స్వాగతం",
    subtitle: "రైతులు మరియు విక్రేతలను సులభంగా మరియు సురక్షితంగా కలపడం.",
    login: "ID తో లాగిన్ అవ్వండి",
    register: "కొత్త ఖాతాను నమోదు చేయండి",
    dashboard: "డ్యాష్‌బోర్డ్",
    marketplace: "మార్కెట్‌ప్లేస్",
    matches: "నా మ్యాచ్‌లు",
    chat: "సందేశాలు",
    profile: "ప్రొఫైల్",
    assistant: "అగ్రో-బాట్ AI",
    logout: "లాగ్ అవుట్",
    farmer: "రైతు",
    vendor: "విక్రేత",
    selectRole: "మీ పాత్రను ఎంచుకోండి",
    cropsGrown: "నేను పండించే పంటలు",
    cropsNeeded: "నాకు కావాల్సిన పంటలు",
    price: "ధర",
    area: "రాష్ట్రం / ప్రాంతం",
    save: "వివరాలను సేవ్ చేయండి",
    trustScore: "నమ్మక స్కోరు",
    report: "రిపోర్ట్ చేయండి",
    rate: "రేట్ చేయండి",
    sendMessage: "సందేశం పంపండి",
    noMatches: "ఇంకా మ్యాచ్‌లు కనుగొనబడలేదు. మీ అంశాలను నవీకరించడానికి ప్రయత్నించండి.",
    recentChats: "ఇటీవలి చాట్‌లు",
    priceTrend: "మార్కెట్ ధరల సరళి",
    aiPrompt: "పంట ధరలు, వాతావరణం లేదా వ్యవసాయ చిట్కాల గురించి అగ్రో-బాట్‌ను అడగండి...",
    ask: "అడగండి",
    loading: "ఆలోచిస్తోంది...",
    idCopied: "ID కాపీ చేయబడింది! తర్వాత లాగిన్ చేయడానికి దీన్ని సేవ్ చేయండి.",
    anonymous: "మీ అనామక ID",
    enterId: "మీ అనామక ID ని నమోదు చేయండి",
    findMatches: "మ్యాచ్‌లను కనుగొనండి",
    filterByCrop: "పంట ద్వారా ఫిల్టర్ చేయండి",
    userIdNotFound: "వినియోగదారు ID కనుగొనబడలేదు. దయచేసి మొదట నమోదు చేసుకోండి.",
    addOneItem: "దయచేసి కనీసం ఒక పంట/అంశాన్ని జోడించండి.",
    regSuccess: "నమోదు విజయవంతమైంది!",
    goToDashboard: "డ్యాష్‌బోర్డ్‌కు వెళ్లండి",
    realName: "నిజమైన పేరు (ప్రైవేట్)",
    yourName: "మీ పేరు",
    cropType: "పంట రకం",
    quantity: "పరిమాణం",
    addToList: "జాబితాకు జోడించండి",
    added: "జోడించబడింది",
    qtyPlaceholder: "ఉదా. 500 కిలోలు",
    idPlaceholder: "ఉదా. farmer1234",
    welcomeBack: "తిరిగి స్వాగతం,",
    potentialMatches: "సంభావ్య మ్యాచ్‌లు",
    listedItems: "జాబితా చేయబడిన అంశాలు",
    marketTrend: "మార్కెట్ ధోరణి",
    recentMatches: "ఇటీవలి మ్యాచ్‌లు",
    viewAll: "అన్నీ చూడండి",
    grows: "పండిస్తారు",
    needs: "అవసరం",
    perKg: "కిలోకు",
    trust: "నమ్మకం",
    allCrops: "అన్ని పంటలు",
    allLocations: "అన్ని ప్రదేశాలు",
    noMatchesCriteria: "ఈ ప్రమాణాలకు సరిపోయే రైతులు లేదా విక్రేతలు కనుగొనబడలేదు.",
    noConversations: "ఇంకా సంభాషణలు లేవు.",
    tapToChat: "చాట్ చేయడానికి నొక్కండి",
    online: "ఆన్‌లైన్",
    typeMessage: "సందేశాన్ని టైప్ చేయండి...",
    selectConversation: "చాటింగ్ ప్రారంభించడానికి సంభాషణను ఎంచుకోండి",
    editProfile: "ప్రొఫైల్‌ను సవరించండి",
    cancel: "రద్దు చేయండి",
    productInfo: "ఉత్పత్తి సమాచారం",
    add: "జోడించు",
    newItem: "కొత్త అంశం",
    cropLabel: "పంట",
    priceLabel: "ధర",
    qtyLabel: "పరిమాణం",
    noItems: "అంశాలు జాబితా చేయబడలేదు.",
    trustSafety: "నమ్మకం మరియు భద్రత",
    verifiedMember: "ధృవీకరించబడిన సభ్యుడు",
    reviews: "సమీక్షలు",
    writeReview: "సమీక్ష రాయండి...",
    submitReview: "సమీక్షను సమర్పించండి",
    noReviews: "ఇంకా సమీక్షలు లేవు.",
    confirmDelete: "మీరు ఖచ్చితంగా ఈ అంశాన్ని తొలగించాలనుకుంటున్నారా?",
    aiIntro: "నమస్కారం! నేను అగ్రో-బాట్. పంట ధరలు, వ్యవసాయ చిట్కాలు లేదా వాతావరణ సలహాలతో నేను మీకు సహాయం చేయగలను. మీ మనసులో ఏముంది?",
    poweredBy: "జెమిని 2.5 ఫ్లాష్ ద్వారా ఆధారితం",
    aiError: "క్షమించండి, ఆలోచించడంలో నాకు సమస్య ఎదురైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    expandSidebar: "సైడ్‌బార్‌ను విస్తరించండి",
    collapseSidebar: "సైడ్‌బార్‌ను కుదించండి",
    selectOption: "ఎంచుకోండి...",
    photo: "ఫోటో",
    // Crops
    Wheat: "గోధుమలు",
    Rice: "బియ్యం",
    Corn: "మొక్కజొన్న",
    Potatoes: "బంగాళాదుంపలు",
    Tomatoes: "టమోటాలు",
    Onions: "ఉల్లిపాయలు",
    Soybeans: "సోయాబీన్స్",
    Cotton: "పత్తి",
    Sugarcane: "చెరకు",
    Mustard: "ఆవాలు",
    Pulses: "పప్పుధాన్యాలు",
    Spices: "సుగంధ ద్రవ్యాలు"
  },
  [Language.KANNADA]: {
    welcome: "AgroLink ಗೆ ಸ್ವಾಗತ",
    subtitle: "ರೈತರು ಮತ್ತು ಮಾರಾಟಗಾರರನ್ನು ಸರಳವಾಗಿ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಪರ್ಕಿಸುವುದು.",
    login: "ಐಡಿ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ",
    register: "ಹೊಸ ಖಾತೆಯನ್ನು ನೋಂದಾಯಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    matches: "ನನ್ನ ಹೊಂದಾಣಿಕೆಗಳು",
    chat: "ಸಂದೇಶಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    assistant: "ಅಗ್ರೋ-ಬಾಟ್ AI",
    logout: "ಲಾಗ್ ಔಟ್",
    farmer: "ರೈತ",
    vendor: "ಮಾರಾಟಗಾರ",
    selectRole: "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ",
    cropsGrown: "ನಾನು ಬೆಳೆಯುವ ಬೆಳೆಗಳು",
    cropsNeeded: "ನನಗೆ ಬೇಕಾದ ಬೆಳೆಗಳು",
    price: "ಬೆಲೆ",
    area: "ರಾಜ್ಯ / ಪ್ರದೇಶ",
    save: "ವಿವರಗಳನ್ನು ಉಳಿಸಿ",
    trustScore: "ನಂಬಿಕೆ ಸ್ಕೋರ್",
    report: "ವರದಿ ಮಾಡಿ",
    rate: "ರೇಟ್ ಮಾಡಿ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    noMatches: "ಇನ್ನೂ ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ನಿಮ್ಮ ಐಟಂಗಳನ್ನು ನವೀಕರಿಸಲು ಪ್ರಯತ್ನಿಸಿ.",
    recentChats: "ಇತ್ತೀಚಿನ ಚಾಟ್‌ಗಳು",
    priceTrend: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಪ್ರವೃತ್ತಿಗಳು",
    aiPrompt: "ಬೆಳೆ ಬೆಲೆಗಳು, ಹವಾಮಾನ ಅಥವಾ ಕೃಷಿ ಸಲಹೆಗಳ ಬಗ್ಗೆ ಅಗ್ರೋ-ಬಾಟ್ ಅನ್ನು ಕೇಳಿ...",
    ask: "ಕೇಳಿ",
    loading: "ಯೋಚಿಸುತ್ತಿದೆ...",
    idCopied: "ಐಡಿ ಕಾಪಿ ಮಾಡಲಾಗಿದೆ! ನಂತರ ಲಾಗಿನ್ ಮಾಡಲು ಇದನ್ನು ಉಳಿಸಿ.",
    anonymous: "ನಿಮ್ಮ ಅನಾಮಧೇಯ ಐಡಿ",
    enterId: "ನಿಮ್ಮ ಅನಾಮಧೇಯ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ",
    findMatches: "ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಹುಡುಕಿ",
    filterByCrop: "ಬೆಳೆಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    userIdNotFound: "ಬಳಕೆದಾರ ಐಡಿ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ನೋಂದಾಯಿಸಿ.",
    addOneItem: "ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ಬೆಳೆ/ಐಟಂ ಸೇರಿಸಿ.",
    regSuccess: "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    goToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    realName: "ನಿಜವಾದ ಹೆಸರು (ಖಾಸಗಿ)",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    cropType: "ಬೆಳೆ ಪ್ರಕಾರ",
    quantity: "ಪ್ರಮಾಣ",
    addToList: "ಪಟ್ಟಿಗೆ ಸೇರಿಸಿ",
    added: "ಸೇರಿಸಲಾಗಿದೆ",
    qtyPlaceholder: "ಉದಾ. 500 ಕೆಜಿ",
    idPlaceholder: "ಉದಾ. farmer1234",
    welcomeBack: "ಸ್ವಾಗತ,",
    potentialMatches: "ಸಂಭಾವ್ಯ ಹೊಂದಾಣಿಕೆಗಳು",
    listedItems: "ಪಟ್ಟಿ ಮಾಡಲಾದ ಐಟಂಗಳು",
    marketTrend: "ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿ",
    recentMatches: "ಇತ್ತೀಚಿನ ಹೊಂದಾಣಿಕೆಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    grows: "ಬೆಳೆಯುತ್ತಾರೆ",
    needs: "ಅಗತ್ಯವಿದೆ",
    perKg: "ಕೆಜಿಗೆ",
    trust: "ನಂಬಿಕೆ",
    allCrops: "ಎಲ್ಲಾ ಬೆಳೆಗಳು",
    allLocations: "ಎಲ್ಲಾ ಸ್ಥಳಗಳು",
    noMatchesCriteria: "ಈ ಮಾನದಂಡಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ರೈತರು ಅಥವಾ ಮಾರಾಟಗಾರರು ಕಂಡುಬಂದಿಲ್ಲ.",
    noConversations: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ.",
    tapToChat: "ಚಾಟ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    online: "ಆನ್‌ಲೈನ್",
    typeMessage: "ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    selectConversation: "ಚಾಟಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಸಂಭಾಷಣೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    editProfile: "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    productInfo: "ಉತ್ಪನ್ನ ಮಾಹಿತಿ",
    add: "ಸೇರಿಸಿ",
    newItem: "ಹೊಸ ಐಟಂ",
    cropLabel: "ಬೆಳೆ",
    priceLabel: "ಬೆಲೆ",
    qtyLabel: "ಪ್ರಮಾಣ",
    noItems: "ಯಾವುದೇ ಐಟಂಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಲಾಗಿಲ್ಲ.",
    trustSafety: "ನಂಬಿಕೆ ಮತ್ತು ಸುರಕ್ಷತೆ",
    verifiedMember: "ಪರಿಶೀಲಿಸಿದ ಸದಸ್ಯ",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    writeReview: "ವಿಮರ್ಶೆಯನ್ನು ಬರೆಯಿರಿ...",
    submitReview: "ವಿಮರ್ಶೆಯನ್ನು ಸಲ್ಲಿಸಿ",
    noReviews: "ಇನ್ನೂ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ.",
    confirmDelete: "ನೀವು ಈ ಐಟಂ ಅನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    aiIntro: "ನಮಸ್ಕಾರ! ನಾನು ಅಗ್ರೋ-ಬಾಟ್. ಬೆಳೆ ಬೆಲೆಗಳು, ಕೃಷಿ ಸಲಹೆಗಳು ಅಥವಾ ಹವಾಮಾನ ಸಲಹೆಗಳಲ್ಲಿ ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ.",
    poweredBy: "ಜೆಮಿನಿ 2.5 ಫ್ಲ್ಯಾಶ್‌ನಿಂದ ಚಾಲಿತವಾಗಿದೆ",
    aiError: "ಕ್ಷಮಿಸಿ, ಯೋಚಿಸಲು ತೊಂದರೆಯಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    expandSidebar: "ಸೈಡ್‌ಬಾರ್ ವಿಸ್ತರಿಸಿ",
    collapseSidebar: "ಸೈಡ್‌ಬಾರ್ ಕುಗ್ಗಿಸಿ",
    selectOption: "ಆರಿಸಿ...",
    photo: "ಫೋಟೋ",
    // Crops
    Wheat: "ಗೋಧಿ",
    Rice: "ಅಕ್ಕಿ",
    Corn: "ಮೆಕ್ಕೆ ಜೋಳ",
    Potatoes: "ಆಲೂಗಡ್ಡೆ",
    Tomatoes: "ಟೊಮ್ಯಾಟೊ",
    Onions: "ಈರುಳ್ಳಿ",
    Soybeans: "ಸೋಯಾಬೀನ್",
    Cotton: "ಹತ್ತಿ",
    Sugarcane: "ಕಬ್ಬು",
    Mustard: "ಸಾಸಿವೆ",
    Pulses: "ದ್ವಿದಳ ಧಾನ್ಯಗಳು",
    Spices: "ಮಸಾಲೆಗಳು"
  },
  [Language.GUJARATI]: {
    welcome: "AgroLink માં આપનું સ્વાગત છે",
    subtitle: "ખેડૂતો અને વિક્રેતાઓને સરળ અને સુરક્ષિત રીતે જોડવું.",
    login: "આઈડી સાથે લોગિન કરો",
    register: "નવું ખાતું નોંધણી કરો",
    dashboard: "ડેશબોર્ડ",
    marketplace: "માર્કેટપ્લેસ",
    matches: "મારા મેચ",
    chat: "સંદેશાઓ",
    profile: "પ્રોફાઇલ",
    assistant: "એગ્રો-બોટ AI",
    logout: "લોગ આઉટ",
    farmer: "ખેડૂત",
    vendor: "વિક્રેતા",
    selectRole: "તમારી ભૂમિકા પસંદ કરો",
    cropsGrown: "હું ઉગાડું છું તે પાક",
    cropsNeeded: "મને જરૂરી પાક",
    price: "કિંમત",
    area: "રાજ્ય / પ્રદેશ",
    save: "વિગતો સાચવો",
    trustScore: "વિશ્વાસ સ્કોર",
    report: "રિપોર્ટ કરો",
    rate: "રેટ કરો",
    sendMessage: "સંદેશ મોકલો",
    noMatches: "હજી સુધી કોઈ મેચ મળી નથી. તમારી આઇટમ્સ અપડેટ કરવાનો પ્રયાસ કરો.",
    recentChats: "તાજેતરની વાતચીત",
    priceTrend: "બજાર ભાવના વલણો",
    aiPrompt: "પાકના ભાવ, હવામાન અથવા ખેતીની ટીપ્સ વિશે એગ્રો-બોટને પૂછો...",
    ask: "પૂછો",
    loading: "વિચારી રહ્યું છે...",
    idCopied: "આઈડી કોપી કર્યું! પછીથી લોગિન કરવા માટે આ સાચવો.",
    anonymous: "તમારો અનામિક આઈડી",
    enterId: "તમારો અનામિક આઈડી દાખલ કરો",
    findMatches: "મેચ શોધો",
    filterByCrop: "પાક દ્વારા ફિલ્ટર કરો",
    userIdNotFound: "વપરાશકર્તા આઈડી મળ્યું નથી. કૃપા કરીને પહેલા નોંધણી કરો.",
    addOneItem: "કૃપા કરીને ઓછામાં ઓછું એક પાક/આઇટમ ઉમેરો.",
    regSuccess: "નોંધણી સફળ!",
    goToDashboard: "ડેશબોર્ડ પર જાઓ",
    realName: "સાચું નામ (ખાનગી)",
    yourName: "તમારું નામ",
    cropType: "પાકનો પ્રકાર",
    quantity: "જથ્થો",
    addToList: "સૂચિમાં ઉમેરો",
    added: "ઉમેર્યું",
    qtyPlaceholder: "દા.ત. 500 કિલો",
    idPlaceholder: "દા.ત. farmer1234",
    welcomeBack: "સ્વાગત છે,",
    potentialMatches: "સંભવિત મેચ",
    listedItems: "સૂચિબદ્ધ આઇટમ્સ",
    marketTrend: "બજારનો વલણ",
    recentMatches: "તાજેતરની મેચ",
    viewAll: "બધું જુઓ",
    grows: "ઉગાડે છે",
    needs: "જરૂર છે",
    perKg: "પ્રતિ કિલો",
    trust: "વિશ્વાસ",
    allCrops: "બધા પાક",
    allLocations: "બધા સ્થળો",
    noMatchesCriteria: "આ માપદંડો સાથે મેળ ખાતા કોઈ ખેડૂત અથવા વિક્રેતા મળ્યા નથી.",
    noConversations: "હજી સુધી કોઈ વાતચીત નથી.",
    tapToChat: "ચેટ કરવા માટે ટેપ કરો",
    online: "ઓનલાઇન",
    typeMessage: "સંદેશ લખો...",
    selectConversation: "ચેટિંગ શરૂ કરવા માટે વાતચીત પસંદ કરો",
    editProfile: "પ્રોફાઇલ સંપાદિત કરો",
    cancel: "રદ કરો",
    productInfo: "ઉત્પાદન માહિતી",
    add: "ઉમેરો",
    newItem: "નવી આઇટમ",
    cropLabel: "પાક",
    priceLabel: "કિંમત",
    qtyLabel: "જથ્થો",
    noItems: "કોઈ આઇટમ્સ સૂચિબદ્ધ નથી.",
    trustSafety: "વિશ્વાસ અને સુરક્ષા",
    verifiedMember: "ત્યારથી સત્યાપિત સભ્ય",
    reviews: "સમીક્ષાઓ",
    writeReview: "સમીક્ષા લખો...",
    submitReview: "સમીક્ષા સબમિટ કરો",
    noReviews: "હજી સુધી કોઈ સમીક્ષાઓ નથી.",
    confirmDelete: "શું તમે ખાતરી કરો છો કે તમે આ આઇટમ કાઢી નાખવા માંગો છો?",
    aiIntro: "નમસ્તે! હું એગ્રો-બોટ છું. હું તમને પાકના ભાવ, ખેતીની ટીપ્સ અથવા હવામાન સલાહમાં મદદ કરી શકું છું.",
    poweredBy: "જેમિની 2.5 ફ્લેશ દ્વારા સંચાલિત",
    aiError: "માફ કરશો, મને વિચારવામાં તકલીફ પડી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    expandSidebar: "સાઇડબાર વિસ્તૃત કરો",
    collapseSidebar: "સાઇડબાર સંકુચિત કરો",
    selectOption: "પસંદ કરો...",
    photo: "ફોટો",
    // Crops
    Wheat: "ઘઉં",
    Rice: "ચોખા",
    Corn: "મકાઈ",
    Potatoes: "બટાકા",
    Tomatoes: "ટામેટાં",
    Onions: "ડુંગળી",
    Soybeans: "સોયાબીન",
    Cotton: "કપાસ",
    Sugarcane: "શેરડી",
    Mustard: "સરસવ",
    Pulses: "કઠોળ",
    Spices: "મસાલા"
  },
  [Language.PUNJABI]: {
    welcome: "AgroLink ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
    subtitle: "ਕਿਸਾਨਾਂ ਅਤੇ ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਸਰਲ ਅਤੇ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਜੋੜਨਾ।",
    login: "ਆਈਡੀ ਨਾਲ ਲੌਗਇਨ ਕਰੋ",
    register: "ਨਵਾਂ ਖਾਤਾ ਰਜਿਸਟਰ ਕਰੋ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    marketplace: "ਮਾਰਕੀਟਪਲੇਸ",
    matches: "ਮੇਰੇ ਮੈਚ",
    chat: "ਸੁਨੇਹੇ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    assistant: "ਐਗਰੋ-ਬੋਟ ਏਆਈ",
    logout: "ਲੌਗ ਆਉਟ",
    farmer: "ਕਿਸਾਨ",
    vendor: "ਵਿਕਰੇਤਾ",
    selectRole: "ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
    cropsGrown: "ਫਸਲਾਂ ਜੋ ਮੈਂ ਉਗਾਉਂਦਾ ਹਾਂ",
    cropsNeeded: "ਫਸਲਾਂ ਜੋ ਮੈਨੂੰ ਚਾਹੀਦੀਆਂ ਹਨ",
    price: "ਕੀਮਤ",
    area: "ਰਾਜ / ਖੇਤਰ",
    save: "ਵੇਰਵੇ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    trustScore: "ਭਰੋਸਾ ਸਕੋਰ",
    report: "ਰਿਪੋਰਟ ਕਰੋ",
    rate: "ਰੇਟ ਕਰੋ",
    sendMessage: "ਸੁਨੇਹਾ ਭੇਜੋ",
    noMatches: "ਅਜੇ ਤੱਕ ਕੋਈ ਮੈਚ ਨਹੀਂ ਮਿਲਿਆ। ਆਪਣੀਆਂ ਆਈਟਮਾਂ ਨੂੰ ਅਪਡੇਟ ਕਰਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    recentChats: "ਹਾਲੀਆ ਗੱਲਬਾਤ",
    priceTrend: "ਮਾਰਕੀਟ ਕੀਮਤ ਦੇ ਰੁਝਾਨ",
    aiPrompt: "ਫਸਲ ਦੀਆਂ ਕੀਮਤਾਂ, ਮੌਸਮ ਜਾਂ ਖੇਤੀ ਸੁਝਾਵਾਂ ਬਾਰੇ ਐਗਰੋ-ਬੋਟ ਨੂੰ ਪੁੱਛੋ...",
    ask: "ਪੁੱਛੋ",
    loading: "ਸੋਚ ਰਿਹਾ ਹੈ...",
    idCopied: "ਆਈਡੀ ਕਾਪੀ ਕੀਤੀ ਗਈ! ਬਾਅਦ ਵਿੱਚ ਲੌਗਇਨ ਕਰਨ ਲਈ ਇਸਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ।",
    anonymous: "ਤੁਹਾਡੀ ਅਗਿਆਤ ਆਈਡੀ",
    enterId: "ਆਪਣੀ ਅਗਿਆਤ ਆਈਡੀ ਦਰਜ ਕਰੋ",
    findMatches: "ਮੈਚ ਲੱਭੋ",
    filterByCrop: "ਫਸਲ ਦੁਆਰਾ ਫਿਲਟਰ ਕਰੋ",
    userIdNotFound: "ਵਰਤੋਂਕਾਰ ਆਈਡੀ ਨਹੀਂ ਮਿਲੀ। ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਰਜਿਸਟਰ ਕਰੋ।",
    addOneItem: "ਕਿਰਪਾ ਕਰਕੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਫਸਲ/ਆਈਟਮ ਸ਼ਾਮਲ ਕਰੋ।",
    regSuccess: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ!",
    goToDashboard: "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਜਾਓ",
    realName: "ਅਸਲੀ ਨਾਮ (ਨਿੱਜੀ)",
    yourName: "ਤੁਹਾਡਾ ਨਾਮ",
    cropType: "ਫਸਲ ਦੀ ਕਿਸਮ",
    quantity: "ਮਾਤਰਾ",
    addToList: "ਸੂਚੀ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    added: "ਸ਼ਾਮਲ ਕੀਤਾ",
    qtyPlaceholder: "ਉਦਾ. 500 ਕਿਲੋ",
    idPlaceholder: "ਉਦਾ. farmer1234",
    welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ,",
    potentialMatches: "ਸੰਭਾਵੀ ਮੈਚ",
    listedItems: "ਸੂਚੀਬੱਧ ਆਈਟਮਾਂ",
    marketTrend: "ਮਾਰਕੀਟ ਰੁਝਾਨ",
    recentMatches: "ਹਾਲੀਆ ਮੈਚ",
    viewAll: "ਸਭ ਦੇਖੋ",
    grows: "ਉਗਾਉਂਦਾ ਹੈ",
    needs: "ਚਾਹੀਦਾ ਹੈ",
    perKg: "ਪ੍ਰਤੀ ਕਿਲੋ",
    trust: "ਭਰੋਸਾ",
    allCrops: "ਸਾਰੀਆਂ ਫਸਲਾਂ",
    allLocations: "ਸਾਰੇ ਸਥਾਨ",
    noMatchesCriteria: "ਇਹਨਾਂ ਮਾਪਦੰਡਾਂ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਕੋਈ ਕਿਸਾਨ ਜਾਂ ਵਿਕਰੇਤਾ ਨਹੀਂ ਮਿਲਿਆ।",
    noConversations: "ਅਜੇ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ ਹੋਈ।",
    tapToChat: "ਗੱਲਬਾਤ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ",
    online: "ਆਨਲਾਈਨ",
    typeMessage: "ਇਕ ਸੁਨੇਹਾ ਲਿਖੋ...",
    selectConversation: "ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕੋਈ ਗੱਲਬਾਤ ਚੁਣੋ",
    editProfile: "ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    productInfo: "ਉਤਪਾਦ ਜਾਣਕਾਰੀ",
    add: "ਸ਼ਾਮਲ ਕਰੋ",
    newItem: "ਨਵੀੀ ਆਈਟਮ",
    cropLabel: "ਫਸਲ",
    priceLabel: "ਕੀਮਤ",
    qtyLabel: "ਮਾਤਰਾ",
    noItems: "ਕੋਈ ਆਈਟਮ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹੈ।",
    trustSafety: "ਭਰੋਸਾ ਅਤੇ ਸੁਰੱਖਿਆ",
    verifiedMember: "ਤਸਦੀਕਸ਼ੁਦਾ ਮੈਂਬਰ",
    reviews: "ਸਮੀਖਿਆਵਾਂ",
    writeReview: "ਇੱਕ ਸਮੀਖਿਆ ਲਿਖੋ...",
    submitReview: "ਸਮੀਖਿਆ ਦਰਜ ਕਰੋ",
    noReviews: "ਅਜੇ ਕੋਈ ਸਮੀਖਿਆ ਨਹੀਂ।",
    confirmDelete: "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ 'ਤੇ ਇਸ ਆਈਟਮ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    aiIntro: "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ! ਮੈਂ ਐਗਰੋ-ਬੋਟ ਹਾਂ। ਮੈਂ ਫਸਲ ਦੀਆਂ ਕੀਮਤਾਂ, ਖੇਤੀ ਸੁਝਾਵਾਂ ਜਾਂ ਮੌਸਮ ਸਲਾਹ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।",
    poweredBy: "ਜੈਮਿਨੀ 2.5 ਫਲੈਸ਼ ਦੁਆਰਾ ਸੰਚਾਲਿਤ",
    aiError: "ਮਾਫ ਕਰਨਾ, ਮੈਨੂੰ ਸੋਚਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਆਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    expandSidebar: "ਸਾਈਡਬਾਰ ਫੈਲਾਓ",
    collapseSidebar: "ਸਾਈਡਬਾਰ ਸਮੇਟੋ",
    selectOption: "ਚੁਣੋ...",
    photo: "ਫੋਟੋ",
    // Crops
    Wheat: "ਕਣਕ",
    Rice: "ਚੌਲ",
    Corn: "ਮੱਕੀ",
    Potatoes: "ਆਲੂ",
    Tomatoes: "ਟਮਾਟਰ",
    Onions: "ਪਿਆਜ਼",
    Soybeans: "ਸੋਇਆਬੀਨ",
    Cotton: "ਕਪਾਹ",
    Sugarcane: "ਗੰਨਾ",
    Mustard: "ਸਰ੍ਹੋਂ",
    Pulses: "ਦਾਲਾਂ",
    Spices: "ਮਸਾਲੇ"
  },
  [Language.MALAYALAM]: {
    welcome: "AgroLink-ലേക്ക് സ്വാഗതം",
    subtitle: "കർഷകരെയും കച്ചവടക്കാരെയും ലളിതമായും സുരക്ഷിതമായും ബന്ധിപ്പിക്കുന്നു.",
    login: "ഐഡി ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക",
    register: "പുതിയ അക്കൗണ്ട് രജിസ്റ്റർ ചെയ്യുക",
    dashboard: "ഡാഷ്ബോർഡ്",
    marketplace: "മാർക്കറ്റ്പ്ലേസ്",
    matches: "എന്റെ പൊരുത്തങ്ങൾ",
    chat: "സന്ദേശങ്ങൾ",
    profile: "പ്രൊഫൈൽ",
    assistant: "അഗ്രോ-ബോട്ട് AI",
    logout: "ലോഗ് ഔട്ട്",
    farmer: "കർഷകൻ",
    vendor: "കച്ചവടക്കാരൻ",
    selectRole: "നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക",
    cropsGrown: "ഞാൻ കൃഷി ചെയ്യുന്ന വിളകൾ",
    cropsNeeded: "എനിക്ക് ആവശ്യമുള്ള വിളകൾ",
    price: "വില",
    area: "സംസ്ഥാനം / പ്രദേശം",
    save: "വിശദാംശങ്ങൾ സംരക്ഷിക്കുക",
    trustScore: "വിശ്വാസ സ്കോർ",
    report: "റിപ്പോർട്ട് ചെയ്യുക",
    rate: "റേറ്റ് ചെയ്യുക",
    sendMessage: "സന്ദേശം അയക്കുക",
    noMatches: "ഇതുവരെ പൊരുത്തങ്ങളൊന്നും കണ്ടെത്തിയില്ല. നിങ്ങളുടെ ഇനങ്ങൾ അപ്ഡേറ്റ് ചെയ്യാൻ ശ്രമിക്കുക.",
    recentChats: "സമീപകാല ചാറ്റുകൾ",
    priceTrend: "വിപണി വില ട്രെൻഡുകൾ",
    aiPrompt: "വിള വിലകൾ, കാലാവസ്ഥ, അല്ലെങ്കിൽ കാർഷിക നുറുങ്ങുകൾ എന്നിവയെക്കുറിച്ച് അഗ്രോ-ബോട്ടിനോട് ചോദിക്കുക...",
    ask: "ചോദിക്കുക",
    loading: "ചിന്തിക്കുന്നു...",
    idCopied: "ഐഡി കോപ്പി ചെയ്തു! പിന്നീട് ലോഗിൻ ചെയ്യാൻ ഇത് സൂക്ഷിക്കുക.",
    anonymous: "നിങ്ങളുടെ അജ്ഞാത ഐഡി",
    enterId: "നിങ്ങളുടെ അജ്ഞാത ഐഡി നൽകുക",
    findMatches: "പൊരുത്തങ്ങൾ കണ്ടെത്തുക",
    filterByCrop: "വിള അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    userIdNotFound: "ഉപയോക്തൃ ഐഡി കണ്ടെത്തിയില്ല. ദയവായി ആദ്യം രജിസ്റ്റർ ചെയ്യുക.",
    addOneItem: "ദയവായി ഒരു വിള/ഇനം എങ്കിലും ചേർക്കുക.",
    regSuccess: "രജിസ്ട്രേഷൻ വിജയിച്ചു!",
    goToDashboard: "ഡാഷ്ബോർഡിലേക്ക് പോകുക",
    realName: "യഥാർത്ഥ പേര് (സ്വകാര്യം)",
    yourName: "നിങ്ങളുടെ പേര്",
    cropType: "വിളയുടെ തരം",
    quantity: "അളവ്",
    addToList: "ലിസ്റ്റിലേക്ക് ചേർക്കുക",
    added: "ചേർത്തു",
    qtyPlaceholder: "ഉദാ. 500 കിലോ",
    idPlaceholder: "ഉദാ. farmer1234",
    welcomeBack: "സ്വാഗതം,",
    potentialMatches: "സാധ്യമായ പൊരുത്തങ്ങൾ",
    listedItems: "ലിസ്റ്റ് ചെയ്ത ഇനങ്ങൾ",
    marketTrend: "വിപണി പ്രവണത",
    recentMatches: "സമീപകാല പൊരുത്തങ്ങൾ",
    viewAll: "എല്ലാം കാണുക",
    grows: "കൃഷി ചെയ്യുന്നു",
    needs: "ആവശ്യമുണ്ട്",
    perKg: "കിലോയ്ക്ക്",
    trust: "വിശ്വാസം",
    allCrops: "എല്ലാ വിളകളും",
    allLocations: "എല്ലാ സ്ഥലങ്ങളും",
    noMatchesCriteria: "ഈ മാനദണ്ഡങ്ങളുമായി പൊരുത്തപ്പെടുന്ന കർഷകരോ കച്ചവടക്കാരോ കണ്ടെത്തിയില്ല.",
    noConversations: "സംഭാഷണങ്ങളൊന്നുമില്ല.",
    tapToChat: "ചാറ്റ് ചെയ്യാൻ ടാപ്പ് ചെയ്യുക",
    online: "ഓൺലൈൻ",
    typeMessage: "ഒരു സന്ദേശം ടൈപ്പ് ചെയ്യുക...",
    selectConversation: "ചാറ്റിംഗ് ആരംഭിക്കാൻ ഒരു സംഭാഷണം തിരഞ്ഞെടുക്കുക",
    editProfile: "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക",
    productInfo: "ഉൽപ്പന്ന വിവരങ്ങൾ",
    add: "ചേർക്കുക",
    newItem: "പുതിയ ഇനം",
    cropLabel: "വിള",
    priceLabel: "വില",
    qtyLabel: "അളവ്",
    noItems: "ഇനങ്ങളൊന്നും ലിസ്റ്റ് ചെയ്തിട്ടില്ല.",
    trustSafety: "വിശ്വാസവും സുരക്ഷയും",
    verifiedMember: "പരിശോധിച്ച അംഗം",
    reviews: "അവലോകനങ്ങൾ",
    writeReview: "ഒരു അവലോകനം എഴുതുക...",
    submitReview: "അവലോകനം സമർപ്പിക്കുക",
    noReviews: "ഇതുവരെ അവലോകനങ്ങളൊന്നുമില്ല.",
    confirmDelete: "ഈ ഇനം നീക്കംചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
    aiIntro: "നമസ്കാരം! ഞാൻ അഗ്രോ-ബോട്ട്. വിള വിലകൾ, കാർഷിക നുറുങ്ങുകൾ അല്ലെങ്കിൽ കാലാവസ്ഥാ ഉപദേശങ്ങൾ എന്നിവയിൽ എനിക്ക് നിങ്ങളെ സഹായിക്കാനാകും.",
    poweredBy: "ജെമിനി 2.5 ഫ്ലാഷ് നൽകുന്നത്",
    aiError: "ക്ഷമിക്കണം, ചിന്തിക്കാൻ ബുദ്ധിമുട്ടുണ്ടായി. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    expandSidebar: "സൈഡ്‌ബാർ വികസിപ്പിക്കുക",
    collapseSidebar: "സൈഡ്‌ബാർ ചുരുക്കുക",
    selectOption: "തിരഞ്ഞെടുക്കുക...",
    photo: "ഫോട്ടോ",
    // Crops
    Wheat: "ഗോതമ്പ്",
    Rice: "അരി",
    Corn: "ചോളം",
    Potatoes: "ഉരുളക്കിഴങ്ങ്",
    Tomatoes: "തക്കാളി",
    Onions: "ഉള്ളി",
    Soybeans: "സോയാബീൻ",
    Cotton: "പരുത്തി",
    Sugarcane: "കരിമ്പ്",
    Mustard: "കടുക്",
    Pulses: "പരിപ്പ്",
    Spices: "സുഗന്ധവ്യഞ്ജനങ്ങൾ"
  }
};
